### ISSUE TITLE
Nextcloud Sync Error

### ISSUE THREAD

**Issue by quetzalism** [madeofpendletonwool/PinePods#132]
I'm attempting to add my nextcloud that is running gpoddersync to my pinepods. 
![image](https://github.com/madeofpendletonwool/PinePods/assets/111016405/8c797415-fa16-4a7f-9a34-2524a17d2223)

This is the error in the logs when i attempt to authenticate.

`2024-05-08 09:24:54 [2024-05-08 15:24:54] [INFO] - uvicorn.access: 172.30.0.1:0 - "POST /api/data/initiate_nextcloud_login HTTP/1.0" 500
2024-05-08 09:24:54 [2024-05-08 15:24:54] [ERROR] - uvicorn.error: Exception in ASGI application
2024-05-08 09:24:54 Traceback (most recent call last):
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
2024-05-08 09:24:54     result = await app(  # type: ignore[func-returns-value]
2024-05-08 09:24:54              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-05-08 09:24:54     return await self.app(scope, receive, send)
2024-05-08 09:24:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-08 09:24:54     await super().__call__(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-05-08 09:24:54     await self.middleware_stack(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-05-08 09:24:54     raise exc
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-05-08 09:24:54     await self.app(scope, receive, _send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 85, in __call__
2024-05-08 09:24:54     await self.app(scope, receive, send_wrapper)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
2024-05-08 09:24:54     await responder(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
2024-05-08 09:24:54     await self.app(scope, receive, self.send_with_gzip)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-08 09:24:54     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-08 09:24:54     raise exc
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-08 09:24:54     await app(scope, receive, sender)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-05-08 09:24:54     await self.middleware_stack(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-05-08 09:24:54     await route.handle(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-05-08 09:24:54     await self.app(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-05-08 09:24:54     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-08 09:24:54     raise exc
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-08 09:24:54     await app(scope, receive, sender)
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-05-08 09:24:54     response = await func(request)
2024-05-08 09:24:54                ^^^^^^^^^^^^^^^^^^^
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-05-08 09:24:54     raw_response = await run_endpoint_function(
2024-05-08 09:24:54                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-05-08 09:24:54     return await dependant.call(**values)
2024-05-08 09:24:54            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-08 09:24:54   File "/pinepods/clients/clientapi.py", line 2324, in initiate_nextcloud_login
2024-05-08 09:24:54     is_valid_key = database_functions.functions.verify_api_key(cnx, api_key)
2024-05-08 09:24:54                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-08 09:24:54   File "/pinepods/database_functions/functions.py", line 1564, in verify_api_key
2024-05-08 09:24:54     cursor = cnx.cursor()
2024-05-08 09:24:54              ^^^^^^^^^^^^
2024-05-08 09:24:54   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/connection.py", line 1433, in cursor
2024-05-08 09:24:54     raise OperationalError("MySQL Connection not available")
2024-05-08 09:24:54 mysql.connector.errors.OperationalError: MySQL Connection not available`

Any ideas i could try out to fix this so pinepods syncs to nextcloud correctly?

**Comment by quetzalism** [comment]
Just kidding. I was sure I was running the latest version, and i was wrong. 

Quick update fixed the issue. 

Marking as complete.

**Comment by madeofpendletonwool** [comment]
Glad you got it to work! As an aside, in the next few days here I'll be releasing a new version with numerous fixes to UI elements to make the experience more polished. As part of that I've created a news rss feed that you can add to Pinepods like any other podcast. So it should be great for keeping you up to date on changes and the latest version. Keep an eye out!
