### ISSUE TITLE
Nextlouc/Gpodders Sync Errors

### ISSUE THREAD

**Issue by quetzalism** [madeofpendletonwool/PinePods#259]
`2024-08-12 10:45:09 Adding gPodder settings
2024-08-12 10:45:09 [2024-08-12 16:45:09] [ERROR] - uvicorn.error: Exception in ASGI application
2024-08-12 10:45:09 Traceback (most recent call last):
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 398, in run_asgi
2024-08-12 10:45:09     result = await app(  # type: ignore[func-returns-value]
2024-08-12 10:45:09              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
2024-08-12 10:45:09     return await self.app(scope, receive, send)
2024-08-12 10:45:09            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-08-12 10:45:09     await super().__call__(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-08-12 10:45:09     await self.middleware_stack(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-12 10:45:09     raise exc
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-12 10:45:09     await self.app(scope, receive, _send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/sessions.py", line 85, in __call__
2024-08-12 10:45:09     await self.app(scope, receive, send_wrapper)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
2024-08-12 10:45:09     await responder(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
2024-08-12 10:45:09     await self.app(scope, receive, self.send_with_gzip)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-08-12 10:45:09     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-12 10:45:09     raise exc
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-12 10:45:09     await app(scope, receive, sender)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-08-12 10:45:09     await self.middleware_stack(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-08-12 10:45:09     await route.handle(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-08-12 10:45:09     await self.app(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-08-12 10:45:09     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-12 10:45:09     raise exc
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-12 10:45:09     await app(scope, receive, sender)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
2024-08-12 10:45:09     await response(scope, receive, send)
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/responses.py", line 162, in __call__
2024-08-12 10:45:09     await self.background()
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/background.py", line 45, in __call__
2024-08-12 10:45:09     await task()
2024-08-12 10:45:09   File "/opt/venv/lib/python3.11/site-packages/starlette/background.py", line 28, in __call__
2024-08-12 10:45:09     await self.func(*self.args, **self.kwargs)
2024-08-12 10:45:09   File "/pinepods/clients/clientapi.py", line 3185, in poll_for_auth_completion_background
2024-08-12 10:45:09     result = database_functions.functions.add_gpodder_settings(database_type, cnx, data.user_id, str(data.nextcloud_url), credentials["appPassword"], credentials["loginName"], "nextcloud")
2024-08-12 10:45:09              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

I am using the latest nextcloud and the most up to date version of Pinepods and Gpoddersync Plugin for Nextcloud.

I am unable to sync with nextcloud and I have provided the error from the logs.

When i attempt to authenticate with my nextcloud url everything seems to work and i get the message from nextcloud saying "Account Connected you may close this window" but the Pinepod page does not update and simply shows: 
"Current Podcast Sync Server: Not currently syncing with Nextcloud server"

**Comment by madeofpendletonwool** [comment]
Hi there! Great find. I just fixed this in #264. The issue was due to a missed placeholder for a var when ran via mysql database. This will roll out with the next update!
